FILE FREEFORM = 03DED53E-BECD-428F-9F79-5ABA64C58445 {
        SECTION UI = "battery_symbol_Nocharger.bmp"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-03ded53e-becd-428f-9f79-5aba64c58445\section1.raw
}

FILE FREEFORM = 07777D7D-677F-47F4-A1FB-3BB1E08E607A {
        SECTION UI = "Panel_sdx55_sharp_4k_dsc_cmd.xml"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-07777d7d-677f-47f4-a1fb-3bb1e08e607a\section1.raw
}

FILE FREEFORM = 0AE323D6-2EBE-11E8-8349-9BA636A0D80C {
        SECTION UI = "Panel_sharp_1080p_cmd.xml"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-0ae323d6-2ebe-11e8-8349-9ba636a0d80c\section1.raw
}

FILE FREEFORM = 13AC9DC9-0092-4374-AE1A-06FF35950FD0 {
        SECTION UI = "Panel_truly_wqxga_dsc_vid.xml"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-13ac9dc9-0092-4374-ae1a-06ff35950fd0\section1.raw
}

FILE FREEFORM = 13E35E77-F1E0-4639-9021-70CBA62FB897 {
        SECTION UI = "Panel_sdx55_truly_wqxga_dual_vid.xml"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-13e35e77-f1e0-4639-9021-70cba62fb897\section1.raw
}

FILE FREEFORM = 151F4DFB-643B-418D-ACB3-A66BC8D7A4EF {
        SECTION UI = "Panel_sdx55_sharp_4k_dsc_vid.xml"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-151f4dfb-643b-418d-acb3-a66bc8d7a4ef\section1.raw
}

FILE FREEFORM = 19B58ACD-B1F8-4078-B9A5-A33584B680E2 {
        SECTION UI = "Panel_sharp_4k_dsc_vid.xml"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-19b58acd-b1f8-4078-b9a5-a33584b680e2\section1.raw
}

FILE FREEFORM = 21E9BDD9-6C3F-4F10-84A5-BBEC322741F1 {
        SECTION UI = "uefipil.cfg"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-21e9bdd9-6c3f-4f10-84a5-bbec322741f1\section1.raw
}

FILE FREEFORM = 2BCA3B86-E175-4609-AC7F-207908B89C75 {
        SECTION UI = "Panel_primary_sharp_1080p_cmd.xml"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-2bca3b86-e175-4609-ac7f-207908b89c75\section1.raw
}

FILE FREEFORM = 2FD70D55-C89A-47C8-A960-5A3AAA10426C {
        SECTION UI = "Panel_sdx55_truly_wqxga_dual_cmd.xml"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-2fd70d55-c89a-47c8-a960-5a3aaa10426c\section1.raw
}

FILE FREEFORM = 32C7620B-9746-4BB6-8166-605682A2C58A {
        SECTION UI = "Panel_nt36850_truly_wqhd_cmd.xml"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-32c7620b-9746-4bb6-8166-605682a2c58a\section1.raw
}

FILE FREEFORM = 3E5584ED-05D4-4267-9048-0D47F76F4248 {
        SECTION UI = "battery_plugged_in_low.bmp"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-3e5584ed-05d4-4267-9048-0d47f76f4248\section1.raw
}

FILE FREEFORM = 3FD97907-93F1-4349-AF3C-3B68B0A5E626 {
        SECTION UI = "low_battery.bmp"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-3fd97907-93f1-4349-af3c-3b68b0a5e626\section1.raw
}

FILE FREEFORM = 45A8FDA2-4FAD-4234-BCDA-D1778611CE13 {
        SECTION UI = "Panel_boe_amoled_wqhd_dsc_vid.xml"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-45a8fda2-4fad-4234-bcda-d1778611ce13\section1.raw
}

FILE FREEFORM = 45FE4B7C-150C-45DA-A021-4BEB2048EC6F {
        SECTION UI = "QcomChargerCfg.cfg"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-45fe4b7c-150c-45da-a021-4beb2048ec6f\section1.raw
}

FILE FREEFORM = 4753E815-DDD8-402D-BF69-9B8C4EB7573E {
        SECTION UI = "battery_error.bmp"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-4753e815-ddd8-402d-bf69-9b8c4eb7573e\section1.raw
}

FILE FREEFORM = 87273B42-311D-11E8-9324-DFB2DADFC3D1 {
        SECTION UI = "Panel_truly_1080p_cmd.xml"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-87273b42-311d-11e8-9324-dfb2dadfc3d1\section1.raw
}

FILE FREEFORM = 88CA5ABF-D0AC-4093-A68C-0CFAE1EF9635 {
        SECTION UI = "Panel_boe_amoled_wqhd_dsc_cmd.xml"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-88ca5abf-d0ac-4093-a68c-0cfae1ef9635\section1.raw
}

FILE FREEFORM = 8B86CD38-C772-4FCF-85AA-345B2B3C1AB4 {
        SECTION UI = "battery_plugged_in.bmp"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-8b86cd38-c772-4fcf-85aa-345b2b3c1ab4\section1.raw
}

FILE FREEFORM = 8BC595B7-391A-4A9A-8256-5B9983B30392 {
        SECTION UI = "Panel_sharp_4k_dsc_cmd.xml"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-8bc595b7-391a-4a9a-8256-5b9983b30392\section1.raw
}

FILE FREEFORM = 8CAE2C55-FC5A-410B-812B-8CA22F572F36 {
        SECTION UI = "Panel_truly_wqxga_dsc_cmd.xml"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-8cae2c55-fc5a-410b-812b-8ca22f572f36\section1.raw
}

FILE FREEFORM = 95E7B040-26A2-4511-9ABB-1D95D6DA7082 {
        SECTION UI = "Panel_truly_wqxga_dual_vid.xml"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-95e7b040-26a2-4511-9abb-1d95d6da7082\section1.raw
}

FILE FREEFORM = A1E235DE-E825-4591-9623-C43175811826 {
        SECTION UI = "SecParti.cfg"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-a1e235de-e825-4591-9623-c43175811826\section1.raw
}

FILE FREEFORM = A3607731-F28D-496C-83D3-FB182F885F8C {
        SECTION UI = "Panel_secondary_truly_1080p_cmd.xml"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-a3607731-f28d-496c-83d3-fb182f885f8c\section1.raw
}

FILE FREEFORM = A91D838E-A5FA-4138-825D-455E23030794 {
        SECTION UI = "logo1.bmp"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-a91d838e-a5fa-4138-825d-455e23030794\section1.raw
}

FILE FREEFORM = A91D838E-A5FA-4138-825D-455E2303079E {
        SECTION UI = "BDS_Menu.cfg"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-a91d838e-a5fa-4138-825d-455e2303079e\section1.raw
}

FILE FREEFORM = B0F8D1BE-5353-4812-B1F6-07E7768204CC {
        SECTION UI = "battery_symbol_DebugBoot.bmp"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-b0f8d1be-5353-4812-b1f6-07e7768204cc\section1.raw
}

FILE FREEFORM = BAFD3200-311D-11E8-8651-0FB3CACF38FB {
        SECTION UI = "Panel_truly_1080p_vid.xml"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-bafd3200-311d-11e8-8651-0fb3cacf38fb\section1.raw
}

FILE FREEFORM = C72FB1A9-5527-4E13-BAC4-F671D0330145 {
        SECTION UI = "temperature_warning.bmp"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-c72fb1a9-5527-4e13-bac4-f671d0330145\section1.raw
}

FILE FREEFORM = F780C779-DD7C-47CD-BD1A-5EB414C51704 {
        SECTION UI = "BATTERY.PROVISION"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-f780c779-dd7c-47cd-bd1a-5eb414c51704\section1.raw
}

FILE FREEFORM = F9E8F683-E065-4E09-B4F9-0230D7CECD08 {
        SECTION UI = "battery_symbol_DebugStay.bmp"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-f9e8f683-e065-4e09-b4f9-0230d7cecd08\section1.raw
}

FILE FREEFORM = FC6315F9-F8FE-4222-A1E3-226DF55D7592 {
        SECTION UI = "Panel_truly_wqxga_dual_cmd.xml"
        SECTION RAW = FirmwareBinaries\BOOT.XF.3.0-00527-SM8150LZB-1\file-fc6315f9-f8fe-4222-a1e3-226df55d7592\section1.raw
}