INF QcomPkg/XBLCore/XBLCore.inf

FILE FREEFORM = DDE58710-41CD-4306-DBFB-3FA90BB1D2DD {
    SECTION UI = "uefiplat.cfg"
    SECTION RAW = RawFiles/uefiplat.cfg
}

INF MdeModulePkg/Core/Dxe/DxeMain.inf
INF MdeModulePkg/Universal/PCD/Dxe/Pcd.inf
INF QcomPkg/Drivers/EnvDxe/EnvDxe.inf
INF MdeModulePkg/Universal/ReportStatusCodeRouter/RuntimeDxe/ReportStatusCodeRouterRuntimeDxe.inf
INF MdeModulePkg/Universal/StatusCodeHandler/RuntimeDxe/StatusCodeHandlerRuntimeDxe.inf
INF MsWheaPkg/MsWheaReport/Dxe/MsWheaReportDxe.inf
INF MdeModulePkg/Core/RuntimeDxe/RuntimeDxe.inf
INF ArmPkg/Drivers/CpuDxe/CpuDxe.inf
INF ArmPkg/Drivers/ArmGic/ArmGicDxe.inf
INF ArmPkg/Drivers/TimerDxe/TimerDxe.inf
INF QcomPkg/Drivers/SmemDxe/SmemDxe.inf
INF QcomPkg/Drivers/DALSYSDxe/DALSYSDxe.inf
INF QcomPkg/Drivers/HWIODxe/HWIODxe.inf
INF QcomPkg/Drivers/ChipInfoDxe/ChipInfoDxe.inf
INF QcomPkg/Drivers/PlatformInfoDxe/PlatformInfoDxe.inf
INF QcomPkg/Drivers/HALIOMMUDxe/HALIOMMUDxe.inf
INF EmbeddedPkg/MetronomeDxe/MetronomeDxe.inf
INF QcomPkg/Drivers/ShmBridgeDxe/ShmBridgeDxe.inf
INF QcomPkg/Drivers/TzDxe/ScmDxe.inf
INF QcomPkg/Drivers/GLinkDxe/GLinkDxe.inf
INF QcomPkg/Drivers/ULogDxe/ULogDxe.inf
INF QcomPkg/Drivers/CmdDbDxe/CmdDbDxe.inf
INF QcomPkg/Drivers/NpaDxe/NpaDxe.inf
INF QcomPkg/Drivers/RpmhDxe/RpmhDxe.inf
INF QcomPkg/Drivers/PdcDxe/PdcDxe.inf
INF QcomPkg/Drivers/ClockDxe/ClockDxe.inf
INF QcomPkg/Drivers/TLMMDxe/TLMMDxe.inf
INF QcomPkg/Drivers/SPMIDxe/SPMIDxe.inf
INF QcomPkg/Drivers/I2CDxe/I2CDxe.inf
INF QcomPkg/Drivers/DDRInfoDxe/DDRInfoDxe.inf
INF MdeModulePkg/Universal/ResetSystemRuntimeDxe/ResetSystemRuntimeDxe.inf
INF QcomPkg/Drivers/PmicDxe/PmicDxeWp.inf
INF Sc8180xFamilyPkg/TouchControllerInitDxe/TouchControllerInitDxe.inf
INF MdeModulePkg/Universal/Disk/DiskIoDxe/DiskIoDxe.inf
INF QcomPkg/Drivers/Deprecated/PartitionDxe/PartitionDxe.inf
INF MdeModulePkg/Universal/Disk/UnicodeCollation/EnglishDxe/EnglishDxe.inf
INF MdeModulePkg/Universal/FvSimpleFileSystemDxe/FvSimpleFileSystemDxe.inf
INF QcomPkg/Drivers/SdccDxe/SdccDxe.inf
INF QcomPkg/Drivers/PILDxe/PILDxe.inf
INF QcomPkg/Drivers/CPRDxe/CPRDxe.inf
INF MdeModulePkg/Universal/WatchdogTimerDxe/WatchdogTimer.inf
INF QcomPkg/Drivers/SecurityDxe/SecurityDxe.inf
INF BaseCryptoDriverDxeAARCH64/BaseCryptoDriverDxeAARCH64.inf
INF MdeModulePkg/Universal/SecurityStubDxe/SecurityStubDxe.inf
INF QcomPkg/Drivers/SpiNorDxe/SpiNorDxe.inf
INF MdeModulePkg/Bus/Pci/NvmExpressDxe/NvmExpressDxe.inf
INF MdeModulePkg/Bus/Pci/PciBusDxe/PciBusDxe.inf
INF FatPkg/EnhancedFatDxe/Fat.inf
INF QcomPkg/Drivers/GpiDxe/GpiDxe.inf
INF QcomPkg/Drivers/TzDxe/TzDxe.inf
INF QcomPkg/Drivers/VariableDxe/VariableDxe.inf
INF Sc8180xFamilyPkg/MsEnvDxe/MsEnvDxe.inf
INF QcomPkg/Drivers/DisplayDxe/DisplayDxe.inf
INF MsSurfaceCorePkg/MuBuiltInVarPolicyInstallerDxe/MuBuiltInVarPolicyInstallerDxe.inf
INF MsCorePkg/MuVarPolicyFoundationDxe/MuVarPolicyFoundationDxe.inf
INF MsGraphicsPkg/GopOverrideDxe/GopOverrideDxe.inf
INF QcomPkg/Drivers/QcomWDogDxe/QcomWDogDxe.inf
INF QcomPkg/Drivers/CrashDumpDxe/CrashDumpDxe.inf
INF QcomPkg/Drivers/RawFileSystemDxe/RawFileSystemDxe.inf
INF QcomPkg/Drivers/DppDxe/DppDxe.inf
INF QcomPkg/Drivers/EmbeddedMonotonicCounter/EmbeddedMonotonicCounter.inf
INF EmbeddedPkg/RealTimeClockRuntimeDxe/RealTimeClockRuntimeDxe.inf
INF MdeModulePkg/Universal/PrintDxe/PrintDxe.inf
INF MdeModulePkg/Universal/DevicePathDxe/DevicePathDxe.inf
INF MdeModulePkg/Universal/HiiDatabaseDxe/HiiDatabaseDxe.inf
INF MdeModulePkg/Universal/BdsDxe/BdsDxe.inf
INF QcomPkg/Drivers/SPIDxe/SPIDxe.inf
INF QcomPkg/Drivers/SerialDxe/SerialDxe.inf
INF QcomPkg/Drivers/TsensDxe/TsensDxe.inf
INF QcomPkg/Drivers/AdcDxe/AdcDxe.inf
INF QcomPkg/Drivers/PmicGlinkDxe/PmicGlinkDxe.inf
INF QcomPkg/Drivers/UsbPwrCtrlDxe/UsbPwrCtrlDxe.inf
INF QcomPkg/Drivers/ChargerExDxe/ChargerExDxe.inf
INF QcomPkg/Drivers/TrEEDxe/TpmDxe.inf
INF QcomPkg/Drivers/LimitsDxe/LimitsDxe.inf
INF QcomPkg/Drivers/UsbfnDwc3Dxe/UsbfnDwc3Dxe.inf
INF QcomPkg/Drivers/XhciPciEmulationDxe/XhciPciEmulationDxe.inf
INF QcomPkg/Drivers/XhciDxe/XhciDxe.inf
INF QcomPkg/Drivers/UsbBusDxe/UsbBusDxe.inf
INF QcomPkg/Drivers/UsbKbDxe/UsbKbDxe.inf
INF QcomPkg/Drivers/UsbMassStorageDxe/UsbMassStorageDxe.inf
INF QcomPkg/Drivers/UsbConfigDxe/UsbConfigDxe.inf
INF QcomPkg/Drivers/UsbInitDxe/UsbInitDxe.inf
INF QcomPkg/Drivers/UsbDeviceDxe/UsbDeviceDxe.inf
INF QcomPkg/Drivers/UsbfnChgDxe/UsbfnChgDxe.inf
INF QcomPkg/Drivers/SmbiosDxe/SmbiosDxe.inf
INF MdeModulePkg/Universal/Acpi/AcpiTableDxe/AcpiTableDxe.inf
INF QcomPkg/Drivers/AcpiPlatformDxe/AcpiPlatformDxe.inf
INF QcomPkg/Drivers/PciHostBridgeDxe/PciHostBridgeDxe.inf
INF QcomPkg/Drivers/HashDxe/HashDxe.inf
INF QcomPkg/Drivers/CipherDxe/CipherDxe.inf
INF QcomPkg/Drivers/RNGDxe/RngDxe.inf
INF Sc8180xFamilyPkg/VariablePolicyControlDxe/VariablePolicyControlDxe.inf
INF MsSurfaceCorePkg/MsManufacturingModeDxe/MsManufacturingMode.inf
INF Sc8180xFamilyPkg/CrashDumpModeDxe/CrashDumpModeDxe.inf
INF QcomPkg/Drivers/TrEEDxe/TrEEDxe.inf
INF QcomPkg/Drivers/HSUartDxe/HSUartDxe.inf
INF MsSamSupportPkg/UspTransport/Dxe/UspTransportDxe.inf
INF MsSamSupportPkg/UspHidDxe/UspHidDxe.inf
INF MsSurfaceCorePkg/MsBoardIdInfo/MsBoardIdInfoDxe.inf
INF QcomPkg/Drivers/SmBiosTableDxe/SmBiosTableDxe.inf
INF QcomPkg/Drivers/AdapterInformationDxe/AdapterInformationDxe.inf
INF QcomPkg/Drivers/SimpleTextInOutSerialDxe/SimpleTextInOutSerial.inf
INF MdeModulePkg/Universal/Console/ConPlatformDxe/ConPlatformDxe.inf
INF MdeModulePkg/Universal/Console/ConSplitterDxe/ConSplitterDxe.inf
INF MdeModulePkg/Universal/Console/GraphicsConsoleDxe/GraphicsConsoleDxe.inf
INF MdeModulePkg/Universal/CapsuleRuntimeDxe/CapsuleRuntimeDxe.inf
INF QcomPkg/Drivers/MorPpiDxe/MorPpiDxe.inf
INF SecurityPkg/Tcg/Tcg2Dxe/Tcg2Dxe.inf
INF Sc8180xFamilyPkg/MeasurePlatformFwBlobsDxe/MeasurePlatformFwBlobsDxe.inf
INF QcomPkg/Drivers/FontDxe/FontDxe.inf
INF QcomPkg/Drivers/OSConfigDxe/OSConfigDxe.inf
INF MdeModulePkg/Universal/Acpi/FirmwarePerformanceDataTableDxe/FirmwarePerformanceDxe.inf
INF NetworkPkg/SnpDxe/SnpDxe.inf
INF NetworkPkg/DpcDxe/DpcDxe.inf
INF NetworkPkg/ArpDxe/ArpDxe.inf
INF NetworkPkg/Dhcp4Dxe/Dhcp4Dxe.inf
INF NetworkPkg/Ip4Dxe/Ip4Dxe.inf
INF NetworkPkg/MnpDxe/MnpDxe.inf
INF NetworkPkg/VlanConfigDxe/VlanConfigDxe.inf
INF NetworkPkg/Mtftp4Dxe/Mtftp4Dxe.inf
INF NetworkPkg/TcpDxe/TcpDxe.inf
INF NetworkPkg/Udp4Dxe/Udp4Dxe.inf
INF NetworkPkg/UefiPxeBcDxe/UefiPxeBcDxe.inf
INF QcomPkg/Drivers/UsbMsdDxe/UsbMsdDxe.inf
INF MdeModulePkg/Universal/Acpi/BootGraphicsResourceTableDxe/BootGraphicsResourceTableDxe.inf
INF MdeModulePkg/Universal/MemoryTest/NullMemoryTestDxe/NullMemoryTestDxe.inf
INF MsSurfaceCorePkg/MsManufacturingModeReclaimDxe/MsManufacturingModeReclaimDxe.inf
INF MsWheaPkg/HwErrBert/HwErrBert.inf
INF MsSamSupportPkg/SamCapabilitiesDxe/SamCapabilitiesDxe.inf
INF MsSamSupportPkg/SamMfgModeDxe/SamMfgModeDxe.inf
INF MsSamSupportPkg/PowerSupply/PowerSupply.inf
INF MsSamSupportPkg/TempSensors/TempSensors.inf
INF MsSamSupportPkg/Batteries/Batteries.inf
INF MsSamSupportPkg/SamRealTimeClockDxe/SamRealTimeClockDxe.inf
INF MsSurfaceCorePkg/HidKeyboardDxe/HidKeyboardDxe.inf
INF MsSurfaceCorePkg/SurfaceTouchHidDxe/SurfaceTouchHidDxe.inf
INF MsSurfaceCorePkg/HidMouseAbsolutePointerDxe/HidMouseAbsolutePointerDxe.inf
INF CarinaPkg/GpioButtonsDxe/GpioButtons.inf
INF MsSurfaceCorePkg/MsSmbiosDxe/MsSmbiosDxe.inf
INF MsSurfaceCorePkg/MsCalibrationServicingDxe/MsCalibrationServicingDxe.inf
INF MsSurfaceCorePkg/MsTouchUnlockDxe/MsTouchUnlockDxe.inf
INF PcBdsPkg/MsBootPolicy/MsBootPolicy.inf
INF MsGraphicsPkg/MsEarlyGraphics/Dxe/MsEarlyGraphics.inf
INF Sc8180xFamilyPkg/DisplayHandoffDxe/DisplayHandoffDxe.inf
INF MsGraphicsPkg/RenderingEngineDxe/RenderingEngineDxe.inf
INF MsGraphicsPkg/SimpleWindowManagerDxe/SimpleWindowManagerDxe.inf
INF MsGraphicsPkg/OnScreenKeyboardDxe/OnScreenKeyboardDxe.inf
INF MsGraphicsPkg/MsUiTheme/Dxe/MsUiThemeProtocol.inf
INF MsGraphicsPkg/DisplayEngineDxe/DisplayEngineDxe.inf
INF MdeModulePkg/Universal/SetupBrowserDxe/SetupBrowserDxe.inf
INF MdeModulePkg/Bus/Usb/UsbMouseAbsolutePointerDxe/UsbMouseAbsolutePointerDxe.inf
INF MsSurfaceCorePkg/Application/SurfaceFrontPage/SurfaceFrontPage.inf
INF MsSurfaceCorePkg/Application/BootMenu/BootMenu.inf
INF MsCorePkg/MuCryptoDxe/MuCryptoDxe.inf
INF MsCorePkg/CheckHardwareConnected/CheckHardwareConnected.inf
INF MdeModulePkg/Universal/RegularExpressionDxe/RegularExpressionDxe.inf
INF MsSurfaceCorePkg/MuBuiltInVarPolicyInstallerDxe/CBB497B8-7F8D-48E6-A535-09B71955E669.inf
INF AdvLoggerPkg/AdvancedFileLogger/AdvancedFileLogger.inf
INF DfciPkg/SettingsManager/SettingsManagerDxe.inf
INF SemmPkg/SemmManager/SemmManager.inf
INF DfciPkg/DfciManager/DfciManager.inf
INF DfciPkg/IdentityAndAuthManager/IdentityAndAuthManagerDxe.inf
INF DfciPkg/Application/DfciMenu/DfciMenu.inf
INF SemmPkg/Application/SemmMenu/SemmMenu.inf
INF MsSurfaceCorePkg/MsProtectionPolicyDxe/MsProtectionPolicyDxe.inf
INF MdeModulePkg/Universal/EsrtFmpDxe/EsrtFmpDxe.inf
INF FmpDevicePkg/FmpDxe/2A680B99-B3C8-4B8D-B210-75120EA1A488.inf
INF FmpDevicePkg/FmpDxe/53A9FBCB-9ACA-46E3-B908-951C34EBBAC4.inf
INF FmpDevicePkg/FmpDxe/29B5DCCA-8EBE-43ED-9D1C-BBF7FC430DD7.inf
INF FmpDevicePkg/FmpDxe/EBDE24E9-24A5-44EC-83AE-DBBFA4055883.inf
INF FmpDevicePkg/FmpDxe/05472C14-ACB9-4458-A354-A68357AC3BF0.inf
INF FmpDevicePkg/FmpDxe/B039D930-78B7-47C7-8AE3-C243D51750B5.inf
INF Sc8180xFamilyPkg/ColorbarsDxe/ColorbarsDxe.inf
INF MsSurfaceCorePkg/MsReservedMemoryOpregionDxe/MsReservedMemoryOpregionDxe.inf
INF MsSurfaceCorePkg/SurfaceOA3Dxe/SurfaceOA3.inf
INF MsSurfaceCorePkg/ResetReason/ResetReason.inf
INF MsSamSupportPkg/SamResetReasonDxe/SamResetReasonDxe.inf

FILE FREEFORM = 4BA47E84-4EF7-11E8-AD64-832B78EEA48D {
    SECTION UI = "MS_J_Panel_EDP.xml"
    SECTION RAW = RawFiles/MS_J_Panel_EDP.xml
}


FILE FREEFORM = A1E235DE-E825-4591-9623-C43175811826 {
    SECTION UI = "SecParti.cfg"
    SECTION RAW = RawFiles/SecParti.cfg
}


FILE FREEFORM = 21E9BDD9-6C3F-4F10-84A5-BBEC322741F1 {
    SECTION UI = "uefipil.cfg"
    SECTION RAW = RawFiles/uefipil.cfg
}


FILE FREEFORM = 7BB28B99-61BB-11D5-9A5D-0090273FC14D {
    SECTION RAW = RawFiles/Logo
    SECTION UI = "Logo"
}


FILE FREEFORM = D2AF039E-9F1F-4616-97AF-BE4509A365EA {
    SECTION RAW = RawFiles/Low_Battery
    SECTION UI = "Low Battery"
}


FILE FREEFORM = 7C3A8851-A6D2-445B-A53B-155F867AB4DA {
    SECTION RAW = RawFiles/Too_Hot
    SECTION UI = "Too Hot"
}


FILE FREEFORM = 4FFEE6D5-B396-40F9-9246-7A8E4A821720 {
    SECTION RAW = RawFiles/FirmwareSettingsIndicator
    SECTION UI = "FirmwareSettingsIndicator"
}


FILE FREEFORM = F1E7A352-46AE-4912-92AF-36AB51781D8E {
    SECTION RAW = RawFiles/BootFailIndicator
    SECTION UI = "BootFailIndicator"
}


FILE FREEFORM = AE2D011C-4128-4960-A536-B424CCC3D1EA {
    SECTION RAW = RawFiles/VolumeUpIndicator
    SECTION UI = "VolumeUpIndicator"
}

INF MsSurfaceCorePkg/Override/MdeModulePkg/Universal/BootManagerPolicyDxe/BootManagerPolicyDxe.inf
INF NetworkPkg/Ip6Dxe/Ip6Dxe.inf
INF NetworkPkg/Dhcp6Dxe/Dhcp6Dxe.inf
INF NetworkPkg/Udp6Dxe/Udp6Dxe.inf
INF NetworkPkg/Mtftp6Dxe/Mtftp6Dxe.inf
INF NetworkPkg/DnsDxe/DnsDxe.inf
INF NetworkPkg/HttpDxe/HttpDxe.inf
INF NetworkPkg/HttpUtilitiesDxe/HttpUtilitiesDxe.inf
INF SharedTlsDxeRelease/SharedTlsDxeRelease.inf
INF Ms_Network/Ms_Network.inf
INF MsSurfaceCorePkg/MsSSDEntryLoggerDxe/MsSSDEntryLoggerDxe.inf
INF MsSurfaceCorePkg/VariableDefaults/VariableDefaultsDxe.inf
